# Generated by Django 3.0.5 on 2023-02-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='docker',
            options={'verbose_name': 'Docker', 'verbose_name_plural': 'Docker Commands'},
        ),
        migrations.AlterModelOptions(
            name='git',
            options={'verbose_name': 'Git', 'verbose_name_plural': 'Git Commands'},
        ),
        migrations.AlterModelOptions(
            name='linux',
            options={'verbose_name': 'Linux', 'verbose_name_plural': 'Linux Commands'},
        ),
        migrations.AddField(
            model_name='docker',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='git',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='linux',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='docker',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='git',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='linux',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Codigo'),
        ),
    ]
