# Generated by Django 3.0.5 on 2023-02-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230222_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linux',
            new_name='Command',
        ),
        migrations.AlterModelOptions(
            name='command',
            options={},
        ),
    ]
